services:

  auth-service:
    image: samarth02198/auth-service:latest
    build:
      context: ./authService
      dockerfile: Dockerfile
    env_file:
      - ./authService/.env
    expose:
      - "5000"
    networks:
      - backend-project
    restart: unless-stopped

  profile-service:
    image: samarth02198/profile-service:latest
    build:
      context: ./profileService
      dockerfile: Dockerfile
    env_file:
      - ./profileService/.env
    expose:
      - "6000"
    networks:
      - backend-project
    restart: unless-stopped

  request-service:
    image: samarth02198/request-service:latest
    build:
      context: ./requestService
      dockerfile: Dockerfile
    env_file:
      - ./requestService/.env
    expose:
      - "7000"
    networks:
      - backend-project
    restart: unless-stopped

  chat-service:
    image: samarth02198/chat-service:latest
    build:
      context: ./chatService
      dockerfile: Dockerfile
    env_file:
      - ./chatService/.env
    expose:
      - "8000"
    networks:
      - backend-project
    restart: unless-stopped


  nginx:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./apigateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
      - profile-service
      - request-service
      - chat-service
    networks:
      - backend-project

networks:
  backend-project:
    driver: bridge